### ISSUE TITLE
Funker ikke på Nokia 3310

### ISSUE THREAD

**Issue by andreas-nesheim** [ClaesF0/npm-test#1]
Pls fix >:(

**Comment by ClaesF0** [comment]
Nå er den ike polyfon lenger :((

**Comment by andreas-nesheim** [comment]
DET BLIR FÅ DÅRLI

**Comment by ClaesF0** [comment]
Nå bakoverkompatibel med 3310, og polyfon men da kun på Ericsson GSM 198
